# Generated by Django 4.2.13 on 2024-07-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_major_author_major_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('clubNume', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
