# Generated by Django 4.2.13 on 2024-07-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_event_clubnume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='clubNume',
        ),
    ]
