# Generated by Django 4.2.13 on 2024-07-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_event_clubnume'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='clubName',
            field=models.CharField(default='No Club', max_length=100),
        ),
    ]
