# Generated by Django 4.2.13 on 2024-08-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
