# Generated by Django 4.2.13 on 2024-08-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_major_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='css_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
    ]
